---
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.0.1'
    hooks:
      - id: prettier
        types_or: [yaml, json, javascript, css, markdown]
        always_run: true
        additional_dependencies:
          - prettier@2.8.3
          - prettier-plugin-sort-json@1.0.0
