---
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v4.0.0-alpha.4'
    hooks:
      - id: prettier
        types_or: [yaml, json, javascript, css, markdown]
        always_run: true
        args: [--no-color, --log-level=warn]
        additional_dependencies:
          - 'prettier@3.1.0'
          - 'prettier-plugin-sort-json@3.0.1'

  - repo: https://github.com/codespell-project/codespell
    rev: 'v2.2.6'
    hooks:
      - id: codespell
        exclude: '^src/(package-lock.json|test/openutau-ustx/bulaomeng.ustx.yaml|test/kustomization/labels.json|bin/.*)$'
        args:
          [
            '-Lcrate,ninjs,ans,specif,seh,specifid,deriver,isnt,tye,forin,dependees,rouge,interm,fo,wast,nome,statics,ue,aack,gost,inout,provId,handels,bu,testng,ags,edn,aks,te,decorder,provid,branche,alse,nd,mape,wil,clude',
          ]
