---
repos:
  - repo: 'https://github.com/rbubley/mirrors-prettier'
    rev: 'v3.5.1'
    hooks:
      - id: 'prettier'
        types_or: ['yaml', 'json', 'javascript', 'css', 'markdown']
        always_run: true
        additional_dependencies:
          - 'prettier@3.4.2'
          - 'prettier-plugin-sort-json@4.0.0'
          - 'prettier-plugin-toml@2.0.1'
        pass_filenames: true
        args: ['--no-color', '--log-level=warn', '--write']
  - repo: 'https://github.com/codespell-project/codespell'
    rev: 'v2.4.1'
    hooks:
      - id: 'codespell'
        exclude: '^(package-lock.json|src/test/openutau-ustx/bulaomeng.ustx.yaml|src/test/kustomization/labels.json|src/test/bun-lock/bun.lock.json|src/bin/.*)$'
        args:
          [
            '--ignore-words-list',
            'crate,ninjs,ans,specif,seh,specifid,deriver,isnt,tye,forin,dependees,rouge,interm,fo,wast,nome,statics,ue,aack,gost,inout,provId,handels,bu,testng,ags,edn,aks,te,decorder,provid,branche,alse,nd,mape,wil,clude,wit,flate,omlet,THIRDPARTY,NotIn,notIn,CopyIn,Requestor,requestor,re-use,ofo,abl',
          ]
