#:schema ../../schemas/json/hugo-theme.json
license = "MIT"
licenselink = "https://example.com/mit"
description = "Theme description"
homepage = "https://example.com/theme"
tags = ["blog", "company"]
features = ["some", "awesome", "features"]

[author]
name = "awesomeness"
homepage = "https://example.com/awesomeness"

# If porting an existing theme
[original]
author = "Name of original author"
homepage = "https://example.com/origin-author"
repo = "https://example.com/origin-theme"
