#:schema ../../schemas/json/hugo-theme.json
name = 100
license = false
licenselink = "Link to theme's license"
description = ["Theme description"]
homepage = "Website of your theme"
tags = ["blog", 29082023]
features = ["some", 9999, "features"]
min_version = "0.59"

authors = [
  "awesomeness<https://example.com/awesomeness>",
  { name = "awesomeless", homepage = "Website of author" },
]

[author]
name = 2023
homepage = "Your website"

# If porting an existing theme
[original]
author = 2022
homepage = "His/Her website"
repo = "Link to source code of original theme"
