#:schema ../../schemas/json/hugo-theme.json
name = "Theme Name"
license = "MIT"
licenselink = "https://example.com/mit"
description = "Theme description"
homepage = "https://example.com/theme"
tags = ["blog", "company"]
features = ["some", "awesome", "features"]
min_version = "0.59.1"

author = [
  { name = "awesomeness", homepage = "https://example.com/awesomeness" },
  { name = "awesomeless", homepage = "https://example.com/awesomeless" },
]

[authors]
name = "awesomeness"
homepage = "https://example.com/awesomeness"
