#:schema ../../schemas/json/pyproject.json
[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools >= 64.0", "setuptools-scm[toml] >= 6.2", "wheel"]

[project]
name = "dynamic-package"
version = "v42.0.1"
description = "An example dynamic package"
dynamic = ["version"]
