name: 'Maintenance: Codeowners Detection and Mention'
on:
  pull_request_target: { types: [opened] }
  issue_comment: { types: [created] }
  pull_request_review: { types: [submitted] }

jobs:
  codeowners-merge:
    if: "github.repository == 'SchemaStore/schemastore' && github.event.pull_request.draft == false"
    runs-on: ubuntu-latest
    permissions: 'write-all'
    steps:
      - uses: 'actions/checkout@v6'
      - name: 'Run Codeowners check'
        uses: 'OSS-Docs-Tools/code-owner-self-merge@9f01f6d51b10a0e0a12300cdd614c9fa80787868'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          merge_method: 'squash'
          ownerNoPings: '["@hyperupcall"]'
