name: 'Maintenance: precommit checks'

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    name: Run pre-commit checks
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5

      # Enablement of https://pre-commit.ci is desirable as it also
      # enable auto-fixes for formatting violations. Still we still want to run
      # our own GitHub action, just in case the external service becomes
      # unavailable.
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install pre-commit
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade pre-commit
      - name: Run pre-commit
        run: |
          pre-commit run --all-files
